### ISSUE TITLE
Need to re-publish to npm with latest changes

### ISSUE THREAD

**Issue by chrishyle** [lightsofapollo/sinon-expect#4]
`.calledWithMatch` (landed during #2) is not in the [npm version](https://www.npmjs.com/package/sinon-expect) of this module. =(

**Comment by chrishyle** [comment]
Hi @lightsofapollo - Can you help out here? this is a pain in the neck for my team, and should be a quick fix!

**Comment by lightsofapollo** [comment]
Done and I have added you as a collaborator here (I don't use this package anymore) ... Would be happy to add you to the npm owners list as well if you wish to commit/push here ;)
